pipelines:
  branches:
    master:
      - step:
          name: Run tests
          image: python:2.7.14
          script:
            - python --version
            - echo "Testing"
            - pip install requests  # for slack_alert
            - bash ci/get_commit_json.sh > /tmp/commit.json
            - pip install -r requirements_test.txt
            - pytest && echo "Test pass" || (python ci/slack_alert.py; exit 1)
            #- echo "Packaging"
            #- pip install twine wheel
            #- bash ci/build_deploy.sh  # Deploy to pip
