region: ap-southeast-2
description: "IAM Policies"
stackname: ExampleStacks-IAM-Policies
parameters:
    VPCStack: {Description: VPC Stack, type: String, value: ExampleStacks-VPC}
mappings: {}
resources:
    iam_policies:
        Policies:
            - Name: "God"
              Roles: ["roles-Roles-StackCreator"]
              Groups: []
              PolicyDocument: |
                                {
                                    "Effect": "Allow",
                                    "Action": "*",
                                    "Resource": "*"
                                }