region: ap-southeast-2
description: "IAM User"
stackname: ExampleStacks-IAM-Users
parameters:
    VPCStack: {Description: VPC Stack, type: String, value: ExampleStacks-VPC}
mappings: {}
resources: 
    iam_users:
        Users:
            IAM-F.Last: {Groups: ["StackCreators"]}
            IAM-First.Last: {Groups: ["StackCreators"]}
        Groups:
            StackCreators: {}

