region: ap-southeast-2
description: rolling
stackname: ExampleStacks-IAM-Roles
parameters:
    VPCStack: {Deccription: VPC Stack, type: String, value: ExampleStacks-VPC}
mappings: {}
resources:
    iam_roles:
        Roles:
            StackCreatorAssume:
            StackCreator:
                MFA_Required: "True"
                ReverseTrust: ["arn:aws:iam::012345678910:root"]
                DependsOn: "StackCreatorAssume"
        InstanceProfiles:
            BuildAgentRole: 
                Type: ec2
                ManagedPolicys: ["AmazonEC2ContainerServiceFullAccess","AmazonEC2FullAccess","AmazonS3FullAccess","AmazonRoute53FullAccess"]



