description: "S3 Policy Example"
region: "ap-southeast-2"
stackname: "ExampleStacks-S3-Policy-Example"
parameters: {}
mappings: {}
resources:
  s3_policies:
    example.lambda.functions:
      policy: |
                "Bucket" : {"Ref" : "myExampleBucket"},
                "PolicyDocument": {
                  "Statement":[{
                    "Action":["s3:GetObject"],
                    "Effect":"Allow",
                    "Resource": "arn:aws:s3:::your-bucket-name/*"
                    "Principal":"*",
                    "Condition":{
                      "StringLike":{
                        "aws:Referer":[
                          "http://www.example.com/*",
                          "http://example.com/*"
                        ]
                      }
                    }
                  }]
                }