description: "Example SecurityGroups"
region: "ap-southeast-2"
stackname: ExampleStacks-SecurityGroups
parameters:
  CoreIpRange: {Description: Core, Type: String, Default: 10.0.0.0/8}
  ServerIpRange: {Description: Mi9 Equinix,Type: String,Default: 192.168.96.0/20}
  GlobalIpRange: {Description: Global IPRange, Type: String, Default: 0.0.0.0/0}
  DirectConnectIpRange: {Description: Direct Connect Peer IPRange, Type: String, Default: 169.254.247.0/24}
  VPCStack: {Description: VPC Stack, Type: String, Default: ExampleStacks-VPC}
mappings: {}
resources:
    securitygroups:
        SquidSecurity:
            sg_description: Squid Firewall Rules
            ingress:
            - [icmp,-1,-1,CoreIpRange]
            - [icmp,-1,-1,ServerIpRange]
            - [icmp,-1,-1,DirectConnectIpRange]
            - [tcp,22,22,CoreIpRange]
            - [tcp,53,53,CoreIpRange]
            - [udp,53,53,CoreIpRange]
            - [tcp,80,80,CoreIpRange]
            - [tcp,443,443,CoreIpRange]
            - [udp,123,123,CoreIpRange]
            egress:
            - [icmp,-1,-1,CoreIpRange]
            - [icmp,-1,-1,ServerIpRange]
            - [icmp,-1,-1,DirectConnectIpRange]
            - [tcp,53,53,GlobalIpRange]
            - [udp,53,53,GlobalIpRange]
            - [udp,123,123,GlobalIpRange]
            - [tcp,80,80,GlobalIpRange]
            - [tcp,443,443,GlobalIpRange]
        BindSecurity:
            sg_description: Bind Firewall Rules
            ingress:
            - [icmp,-1,-1,CoreIpRange]
            - [icmp,-1,-1,ServerIpRange]
            - [icmp,-1,-1,DirectConnectIpRange]
            - [tcp,22,22,CoreIpRange]
            - [tcp,22,22,ServerIpRange]
            - [tcp,53,53,CoreIpRange]
            - [udp,53,53,CoreIpRange]
            - [tcp,53,53,ServerIpRange]
            - [udp,53,53,ServerIpRange]
            egress:
            - [icmp,-1,-1,CoreIpRange]
            - [icmp,-1,-1,ServerIpRange]
            - [icmp,-1,-1,DirectConnectIpRange]
            - [tcp,80,80,GlobalIpRange]
            - [tcp,443,443,GlobalIpRange]
            - [tcp,53,53,GlobalIpRange]
            - [udp,53,53,GlobalIpRange]
            - [udp,123,123,GlobalIpRange]
        EFSSecurity:
            sg_description: TeamCityServer Rules
            ingress:
            - [tcp,22,22,ServerIpRange]
            - [tcp,2049,2049,ServerIpRange]
            - [udp,2049,2049,ServerIpRange]
            - [tcp,111,111,ServerIpRange]
            - [udp,111,111,ServerIpRange]
            - [tcp,4045,4045,ServerIpRange]
            - [udp,4045,4045,ServerIpRange]
            - [tcp,32765,32768,ServerIpRange]
            - [udp,32765,32768,ServerIpRange]
            egress:
            - [tcp,22,22,ServerIpRange]
            - [tcp,2049,2049,ServerIpRange]
            - [udp,2049,2049,ServerIpRange]
            - [tcp,111,111,ServerIpRange]
            - [udp,111,111,ServerIpRange]
            - [tcp,4045,4045,ServerIpRange]
            - [udp,4045,4045,ServerIpRange]
            - [tcp,32765,32768,ServerIpRange]
            - [udp,32765,32768,ServerIpRange]